# Generated by Django 3.2.3 on 2021-05-16 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя категории')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Производитель')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя подкатегории')),
            ],
        ),
        migrations.CreateModel(
            name='VideoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('product_image', models.ImageField(blank=True, upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('processor', models.CharField(max_length=150, verbose_name='Марка процессора')),
                ('memory_value', models.IntegerField(verbose_name='Объем встроенной памяти')),
                ('connectors', models.CharField(max_length=255, verbose_name='Разъемы подключения')),
                ('connectors_number', models.IntegerField(verbose_name='Кол-во подключаемых мониторов')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Категория продукта')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.manufacturer', verbose_name='Производитель продута')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subcategory', verbose_name='Подкатегория продукта')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('product_image', models.ImageField(blank=True, upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('processor', models.CharField(max_length=150, verbose_name='Марка процессора')),
                ('ram_value', models.IntegerField(verbose_name='Объем оперативной памяти')),
                ('memory_value', models.IntegerField(verbose_name='Объем встроенной памяти')),
                ('resolution_screen', models.CharField(max_length=150, verbose_name='Разрешение экрана')),
                ('battery_capacity', models.IntegerField(verbose_name='Емкость аккумулятора')),
                ('nfc', models.BooleanField(verbose_name='NFC')),
                ('os_system', models.CharField(max_length=150, verbose_name='Операционная система')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Категория продукта')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.manufacturer', verbose_name='Производитель продута')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subcategory', verbose_name='Подкатегория продукта')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NoteBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('product_image', models.ImageField(blank=True, upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('processor', models.CharField(max_length=150, verbose_name='Марка процессора')),
                ('ram_value', models.IntegerField(verbose_name='Объем оперативной памяти')),
                ('memory_value', models.IntegerField(verbose_name='Объем встроенной памяти')),
                ('resolution_screen', models.CharField(max_length=150, verbose_name='Разрешение экрана')),
                ('battery_capacity', models.IntegerField(verbose_name='Емкость аккумулятора')),
                ('video_card', models.CharField(blank=True, max_length=150, verbose_name='Видеокарта')),
                ('os_system', models.CharField(blank=True, max_length=150, verbose_name='Операционная система')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Категория продукта')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.manufacturer', verbose_name='Производитель продута')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subcategory', verbose_name='Подкатегория продукта')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HddDisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('product_image', models.ImageField(blank=True, upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('interface', models.CharField(max_length=150, verbose_name='Интерфейс')),
                ('memory_value', models.IntegerField(verbose_name='Объем памяти')),
                ('units_of_measurement', models.CharField(max_length=255, verbose_name='Единицы измерения')),
                ('product_type', models.CharField(max_length=150, verbose_name='HDD/SSD/M2')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Категория продукта')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.manufacturer', verbose_name='Производитель продута')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subcategory', verbose_name='Подкатегория продукта')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
