# Generated by Django 3.2.3 on 2021-05-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug_url',
            field=models.SlugField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hdddisk',
            name='slug_url',
            field=models.SlugField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='slug_url',
            field=models.SlugField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='notebook',
            name='slug_url',
            field=models.SlugField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='slug_url',
            field=models.SlugField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slug_url',
            field=models.SlugField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='videocard',
            name='slug_url',
            field=models.SlugField(max_length=20, null=True, unique=True),
        ),
    ]
