# Generated by Django 3.2.3 on 2021-05-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210517_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='slug_url',
            field=models.SlugField(max_length=20, unique=True),
        ),
    ]
