# Generated by Django 3.2.3 on 2021-05-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_manufacturer_slug_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdddisk',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
